// Research data sources the lab can connect to their brain.
// Structured as a catalog; grouped into Connected / Free / Premium / Reference Managers.

export type SourceTier = "free" | "premium" | "reference-manager" | "preprint" | "dataset";
export type SourceStatus = "connected" | "available" | "institutional-required" | "coming-soon";
export type SourceCategory =
  | "open-access"
  | "preprints"
  | "publisher"
  | "abstracting"
  | "reference-manager"
  | "datasets"
  | "code-and-models"
  | "patents";

export interface DataSource {
  id: string;
  name: string;
  shortName?: string;
  provider?: string;
  description: string;
  tier: SourceTier;
  category: SourceCategory;
  status: SourceStatus;
  connectedAt?: string;
  connectedBy?: string; // team member id
  coverage: { label: string; value: string }[];
  notes?: string;
  // Visual monogram
  mono: string; // 2-letter code
  accent: string; // tailwind gradient class pair
  website?: string;
  requiresAuth?: "oauth" | "api-key" | "institutional-sso" | "none";
  pricingHint?: string;
}

export const dataSources: DataSource[] = [
  // ===== Connected (seed the demo with 3 already live) =====
  {
    id: "arxiv",
    name: "arXiv",
    provider: "Cornell University · Open",
    description: "Preprint repository for physics, math, CS, quantitative biology, and statistics. Real-time feed; 10,000+ new submissions monthly.",
    tier: "preprint",
    category: "preprints",
    status: "connected",
    connectedAt: "2026-02-14T10:00:00Z",
    connectedBy: "m-hiro",
    coverage: [
      { label: "Papers", value: "2.4M" },
      { label: "Domains", value: "Physics · CS · Math · q-bio · stat" },
      { label: "Fulltext", value: "100% (PDF)" },
    ],
    mono: "aX",
    accent: "from-red-600 to-red-800",
    website: "https://arxiv.org",
    requiresAuth: "none",
    pricingHint: "Free · Public",
  },
  {
    id: "pubmed",
    name: "PubMed / PMC",
    provider: "NIH · NLM",
    description: "Biomedical and life sciences citation database. PMC adds 9M+ full-text articles for free.",
    tier: "free",
    category: "open-access",
    status: "connected",
    connectedAt: "2025-11-02T14:30:00Z",
    connectedBy: "m-priya",
    coverage: [
      { label: "Citations", value: "36M" },
      { label: "Full-text (PMC)", value: "9M+" },
      { label: "Domains", value: "Biomedical · Life sciences" },
    ],
    mono: "PM",
    accent: "from-sky-600 to-blue-700",
    website: "https://pubmed.ncbi.nlm.nih.gov",
    requiresAuth: "api-key",
    pricingHint: "Free · NCBI E-utilities",
  },
  {
    id: "biorxiv",
    name: "bioRxiv",
    provider: "Cold Spring Harbor Lab",
    description: "Preprint repository for biology — the dominant source of fresh extremophile, structural biology, and bioinformatics preprints.",
    tier: "preprint",
    category: "preprints",
    status: "connected",
    connectedAt: "2026-04-15T09:00:00Z",
    connectedBy: "m-marcus",
    coverage: [
      { label: "Papers", value: "300K+" },
      { label: "Daily new", value: "~250" },
      { label: "Domains", value: "Biology · Medicine (medRxiv)" },
    ],
    mono: "bX",
    accent: "from-emerald-600 to-teal-700",
    website: "https://www.biorxiv.org",
    requiresAuth: "none",
    pricingHint: "Free · Public",
  },

  // ===== Free / Open =====
  {
    id: "openalex",
    name: "OpenAlex",
    provider: "OurResearch",
    description: "Open bibliographic database successor to Microsoft Academic Graph. Normalized author, institution, concept metadata across 250M+ works.",
    tier: "free",
    category: "abstracting",
    status: "available",
    coverage: [
      { label: "Works", value: "250M" },
      { label: "Authors", value: "90M" },
      { label: "Institutions", value: "109K" },
    ],
    mono: "OA",
    accent: "from-indigo-500 to-indigo-700",
    website: "https://openalex.org",
    requiresAuth: "api-key",
    pricingHint: "Free · Polite pool email required",
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    provider: "Allen Institute for AI",
    description: "AI-powered research discovery. TLDR summaries, citation context sentences, and influential-citations signals. Strong CS and biomedical coverage.",
    tier: "free",
    category: "abstracting",
    status: "available",
    coverage: [
      { label: "Papers", value: "200M" },
      { label: "With TLDR", value: "~60M" },
      { label: "Citation context", value: "Yes" },
    ],
    mono: "S2",
    accent: "from-violet-500 to-fuchsia-600",
    website: "https://www.semanticscholar.org",
    requiresAuth: "api-key",
    pricingHint: "Free · 100 req/s with API key",
  },
  {
    id: "medrxiv",
    name: "medRxiv",
    provider: "CSH Lab · BMJ · Yale",
    description: "Preprint repository for medical research. Complement to bioRxiv for clinical and public health domains.",
    tier: "preprint",
    category: "preprints",
    status: "available",
    coverage: [
      { label: "Papers", value: "55K" },
      { label: "Daily new", value: "~80" },
      { label: "Domains", value: "Medicine · Public health" },
    ],
    mono: "mX",
    accent: "from-cyan-600 to-sky-700",
    website: "https://www.medrxiv.org",
    requiresAuth: "none",
    pricingHint: "Free · Public",
  },
  {
    id: "chemrxiv",
    name: "ChemRxiv",
    provider: "ACS · RSC · GDCh · CSJ · CCS",
    description: "Preprint server for chemistry. Relevant to the lab's biocatalysis and protein engineering cross-overs.",
    tier: "preprint",
    category: "preprints",
    status: "available",
    coverage: [
      { label: "Papers", value: "26K" },
      { label: "Domains", value: "Chemistry · Materials" },
    ],
    mono: "cX",
    accent: "from-amber-500 to-orange-600",
    website: "https://chemrxiv.org",
    requiresAuth: "none",
    pricingHint: "Free · Public",
  },
  {
    id: "core",
    name: "CORE",
    provider: "Open University",
    description: "World's largest aggregator of open-access research. Full-text searchable.",
    tier: "free",
    category: "open-access",
    status: "available",
    coverage: [
      { label: "Papers", value: "300M+" },
      { label: "Full-text", value: "40M+" },
      { label: "Repositories", value: "11K" },
    ],
    mono: "CR",
    accent: "from-lime-600 to-emerald-700",
    website: "https://core.ac.uk",
    requiresAuth: "api-key",
    pricingHint: "Free · Rate-limited by plan",
  },
  {
    id: "crossref",
    name: "Crossref",
    provider: "PILA",
    description: "Authoritative DOI registry and citation metadata. Use for canonical references, versioning, and relationship links.",
    tier: "free",
    category: "abstracting",
    status: "available",
    coverage: [
      { label: "Registered DOIs", value: "160M" },
      { label: "Publishers", value: "18K" },
    ],
    mono: "cR",
    accent: "from-teal-500 to-cyan-700",
    website: "https://www.crossref.org",
    requiresAuth: "none",
    pricingHint: "Free · Polite pool",
  },
  {
    id: "zenodo",
    name: "Zenodo",
    provider: "CERN · OpenAIRE",
    description: "General-purpose repository for datasets, software, preprints, and supplementary materials. Each upload gets a DOI.",
    tier: "dataset",
    category: "datasets",
    status: "available",
    coverage: [
      { label: "Deposits", value: "5M+" },
      { label: "Types", value: "Data · Code · Publications" },
    ],
    mono: "ze",
    accent: "from-sky-500 to-blue-700",
    website: "https://zenodo.org",
    requiresAuth: "oauth",
    pricingHint: "Free",
  },
  {
    id: "huggingface",
    name: "HuggingFace Hub",
    provider: "HuggingFace",
    description: "Models + datasets hub. Relevant for protein language models (ESM-2, etc.) and curated biological datasets.",
    tier: "dataset",
    category: "code-and-models",
    status: "available",
    coverage: [
      { label: "Models", value: "700K+" },
      { label: "Datasets", value: "200K+" },
    ],
    mono: "HF",
    accent: "from-yellow-500 to-amber-600",
    website: "https://huggingface.co",
    requiresAuth: "oauth",
    pricingHint: "Free · Premium tiers for private",
  },
  {
    id: "osf",
    name: "Open Science Framework",
    provider: "Center for Open Science",
    description: "Preregistrations, project archives, and open data hosting. Well-suited for reproducibility records.",
    tier: "free",
    category: "open-access",
    status: "available",
    coverage: [
      { label: "Projects", value: "500K+" },
      { label: "Preregistrations", value: "90K+" },
    ],
    mono: "OS",
    accent: "from-slate-600 to-zinc-800",
    website: "https://osf.io",
    requiresAuth: "oauth",
    pricingHint: "Free",
  },
  {
    id: "ssrn",
    name: "SSRN",
    provider: "Elsevier",
    description: "Social science and economics preprints; selected legal, life sciences, and humanities papers.",
    tier: "preprint",
    category: "preprints",
    status: "available",
    coverage: [
      { label: "Papers", value: "1.5M" },
      { label: "Domains", value: "Social sci · Econ · Law" },
    ],
    mono: "SS",
    accent: "from-zinc-500 to-zinc-700",
    website: "https://www.ssrn.com",
    requiresAuth: "oauth",
    pricingHint: "Free · Some papers paywalled",
  },
  {
    id: "doaj",
    name: "DOAJ",
    provider: "Directory of Open Access Journals",
    description: "Curated index of peer-reviewed open-access journals. Useful as a quality filter on open-access results.",
    tier: "free",
    category: "open-access",
    status: "available",
    coverage: [
      { label: "Journals", value: "20K" },
      { label: "Articles", value: "9M+" },
    ],
    mono: "DJ",
    accent: "from-rose-500 to-pink-700",
    website: "https://doaj.org",
    requiresAuth: "none",
    pricingHint: "Free",
  },

  // ===== Premium / Subscription =====
  {
    id: "elsevier",
    name: "ScienceDirect · Scopus",
    shortName: "Elsevier",
    provider: "Elsevier",
    description: "ScienceDirect (full-text) + Scopus (abstracts & citations). The largest commercial database in the sciences.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "ScienceDirect articles", value: "18M" },
      { label: "Scopus records", value: "87M" },
      { label: "Journals", value: "27K+" },
    ],
    notes: "UCSF has an institutional subscription — connect via UCSF SSO.",
    mono: "EL",
    accent: "from-orange-600 to-red-700",
    website: "https://www.sciencedirect.com",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "springer-nature",
    name: "Nature Portfolio · SpringerLink",
    shortName: "Springer Nature",
    provider: "Springer Nature",
    description: "Nature, Nat. Commun., Scientific Reports, and all SpringerLink content. Critical for your lab's target publication venues.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Articles", value: "13M" },
      { label: "Journals", value: "3K+" },
    ],
    notes: "Includes the lab's Nat Comm 2024 paper venue.",
    mono: "SN",
    accent: "from-green-700 to-teal-800",
    website: "https://www.nature.com",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "wiley",
    name: "Wiley Online Library",
    provider: "Wiley",
    description: "Major publisher for chemistry, engineering, and life sciences journals. Includes Angewandte Chemie, J. Comp. Chem., and Proteins.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Articles", value: "10M+" },
      { label: "Journals", value: "1.6K+" },
    ],
    mono: "WL",
    accent: "from-blue-700 to-indigo-800",
    website: "https://onlinelibrary.wiley.com",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "web-of-science",
    name: "Web of Science",
    provider: "Clarivate",
    description: "Abstracting and citation index with strong historical coverage. Useful for bibliometric analyses and citation tracing.",
    tier: "premium",
    category: "abstracting",
    status: "institutional-required",
    coverage: [
      { label: "Records", value: "220M" },
      { label: "Cited references", value: "2.5B+" },
    ],
    mono: "WS",
    accent: "from-amber-700 to-orange-800",
    website: "https://www.webofscience.com",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "ieee",
    name: "IEEE Xplore",
    provider: "IEEE",
    description: "Flagship database for electrical engineering, computer science, and adjacent fields.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Papers", value: "6M+" },
      { label: "Conferences", value: "2K+ annually" },
    ],
    mono: "IE",
    accent: "from-blue-800 to-indigo-900",
    website: "https://ieeexplore.ieee.org",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "acm",
    name: "ACM Digital Library",
    provider: "ACM",
    description: "Primary source for CS and HCI conferences. Includes SIGGRAPH, SIGCHI, NeurIPS adjacent venues.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Papers", value: "750K+" },
      { label: "Venues", value: "All major ACM confs" },
    ],
    mono: "AC",
    accent: "from-slate-700 to-zinc-900",
    website: "https://dl.acm.org",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "acs",
    name: "ACS Publications",
    provider: "American Chemical Society",
    description: "Authoritative chemistry journals — JACS, J. Phys. Chem., J. Chem. Theory Comput. (your Lindorff-Larsen 2022 venue).",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Articles", value: "1M+" },
      { label: "Journals", value: "80+" },
    ],
    mono: "CS",
    accent: "from-red-700 to-rose-800",
    website: "https://pubs.acs.org",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "jstor",
    name: "JSTOR",
    provider: "ITHAKA",
    description: "Back-catalog journals in humanities and social sciences. Useful for interdisciplinary historical context.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Articles", value: "12M" },
      { label: "Book chapters", value: "3M+" },
    ],
    mono: "JS",
    accent: "from-rose-700 to-red-800",
    website: "https://www.jstor.org",
    requiresAuth: "institutional-sso",
    pricingHint: "Institutional subscription required",
  },
  {
    id: "cochrane",
    name: "Cochrane Library",
    provider: "Cochrane Collaboration",
    description: "Gold-standard systematic reviews and clinical meta-analyses. Relevant when grounding clinical-translation claims.",
    tier: "premium",
    category: "publisher",
    status: "institutional-required",
    coverage: [
      { label: "Reviews", value: "8K" },
      { label: "Protocols", value: "2.5K" },
    ],
    mono: "CL",
    accent: "from-sky-700 to-blue-900",
    website: "https://www.cochranelibrary.com",
    requiresAuth: "institutional-sso",
    pricingHint: "Subscription or pay-per-view",
  },

  // ===== Reference managers =====
  {
    id: "zotero",
    name: "Zotero",
    provider: "Corporation for Digital Scholarship",
    description: "Free, open-source reference manager. Sync your lab's existing library and annotations into the brain.",
    tier: "reference-manager",
    category: "reference-manager",
    status: "available",
    coverage: [
      { label: "Lab items", value: "238" },
      { label: "Sync", value: "Bi-directional" },
    ],
    mono: "Zo",
    accent: "from-red-500 to-rose-700",
    website: "https://www.zotero.org",
    requiresAuth: "oauth",
    pricingHint: "Free · Storage tiers available",
  },
  {
    id: "mendeley",
    name: "Mendeley",
    provider: "Elsevier",
    description: "Reference manager with social network features. Good for discovering what your collaborators are reading.",
    tier: "reference-manager",
    category: "reference-manager",
    status: "available",
    coverage: [
      { label: "User libraries", value: "Private" },
      { label: "Sync", value: "Read-only import" },
    ],
    mono: "Me",
    accent: "from-rose-600 to-red-700",
    website: "https://www.mendeley.com",
    requiresAuth: "oauth",
    pricingHint: "Free tier available",
  },
  {
    id: "endnote",
    name: "EndNote",
    provider: "Clarivate",
    description: "Legacy reference manager deeply integrated with Web of Science. Import-only connection.",
    tier: "reference-manager",
    category: "reference-manager",
    status: "available",
    coverage: [
      { label: "Import", value: "RIS / EndNote XML" },
    ],
    mono: "EN",
    accent: "from-amber-600 to-yellow-700",
    website: "https://endnote.com",
    requiresAuth: "api-key",
    pricingHint: "Paid · Often institutional",
  },
  {
    id: "papers",
    name: "Papers",
    provider: "ReadCube",
    description: "Modern reference manager with clean reader UI and AI-assisted discovery. OAuth import.",
    tier: "reference-manager",
    category: "reference-manager",
    status: "coming-soon",
    coverage: [{ label: "Beta", value: "Rolling out Q3 2026" }],
    mono: "Pa",
    accent: "from-indigo-600 to-violet-700",
    website: "https://www.papersapp.com",
    pricingHint: "Subscription",
  },
];
