import type { Notebook } from "../types";

export const notebooks: Notebook[] = [
  {
    id: "nb-r01",
    title: "R01 — Thermostable Enzymes for Industrial Biocatalysis",
    description:
      "NIH R01 proposal integrating computational design, experimental validation, and industrial continuous-flow biocatalysis of extremophile enzymes.",
    mode: "r01",
    status: "draft",
    createdAt: "2026-02-20T10:30:00Z",
    updatedAt: "2026-04-18T07:58:00Z",
    tags: ["r01", "thermostability", "industrial-biocatalysis", "2026-submission"],
    tabs: [
      { id: "notes", label: "Notes" },
      { id: "protocol", label: "Protocol" },
      { id: "relevant", label: "Relevant Items" },
      { id: "metadata", label: "Metadata" },
      { id: "reviewers", label: "Reviewer Prep", userCreated: true, template: "peer-review" },
    ],
    linkedSyntheses: ["syn-thermostability", "syn-forcefield"],
    linkedHypotheses: ["h-1", "h-2", "h-4"],
    collaborators: [
      { memberId: "m-priya", role: "owner", scope: "whole", status: "active" },
      { memberId: "m-hiro", role: "editor", scope: "whole", status: "active" },
      { memberId: "m-marcus", role: "editor", scope: "whole", status: "active" },
      { memberId: "m-okafor", role: "commenter", scope: "whole", status: "invited", invitedAt: "2026-04-17T20:00:00Z" },
    ],
    activity: [
      { id: "act-1", actorId: "m-priya", action: "created notebook from NIH R01 template", at: "2026-02-20T10:30:00Z" },
      { id: "act-2", actorId: "m-hiro", action: "added Significance block", at: "2026-03-02T14:05:00Z", target: "b-signif" },
      { id: "act-3", actorId: "m-marcus", action: "added Innovation block citing Chen 2026", at: "2026-04-18T06:30:00Z", target: "b-innov-2" },
      { id: "act-4", actorId: "m-priya", action: "invited Dr. Okafor (Commenter)", at: "2026-04-17T20:00:00Z" },
      { id: "act-5", actorId: "m-priya", action: "resolved comment on Aim 2 methodology block", at: "2026-04-17T21:15:00Z", target: "b-aim2-method" },
    ],
    comments: [
      {
        id: "c-1",
        threadId: "t-1",
        blockId: "b-aim2-method",
        authorId: "m-hiro",
        body: "Can we tighten the OPC rationale here? We need to preempt a reviewer saying 'why not just use TIP3P as everyone else does?'",
        createdAt: "2026-04-17T18:50:00Z",
        resolved: true,
        replies: [
          {
            id: "c-1-r1",
            authorId: "m-priya",
            body: "Added citation to Dmitri 2025 + Imoto 2023. Also added the 22% artifact-risk framing. Does that land?",
            createdAt: "2026-04-17T21:00:00Z",
          },
          {
            id: "c-1-r2",
            authorId: "m-hiro",
            body: "Yes, much better. Marking resolved.",
            createdAt: "2026-04-17T21:14:00Z",
          },
        ],
      },
      {
        id: "c-2",
        threadId: "t-2",
        blockId: "b-aim3-goal",
        authorId: "m-marcus",
        body: "@Priya this conflicts with the thermostability mechanism in the Aims paragraph — we can't simultaneously argue strict rigidification AND flexible dynamics matter for industrial function. Need to pick.",
        createdAt: "2026-04-18T06:35:00Z",
        resolved: false,
        replies: [],
      },
    ],
    blocks: [
      {
        id: "b-date-kick",
        type: "date-header",
        content: "",
        dateISO: "2026-02-20",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-02-20T10:30:00Z",
        tabId: "notes",
      },
      {
        id: "b-title",
        type: "heading",
        content: "Specific Aims",
        source: "ai-generated",
        authorId: "m-priya",
        createdAt: "2026-02-20T10:30:00Z",
        tabId: "notes",
        tags: ["aims"],
      },
      {
        id: "b-aims-intro",
        type: "text",
        content:
          "Enzymes evolved by hyperthermophilic archaea solve an industrial problem: they remain active in the 70–95 °C reactor conditions used for continuous-flow biocatalysis. But the computational mechanistic picture we (and the field) have relied on — that these enzymes are stable because they are rigid — rests on a solvent-model assumption that the last six months of literature has called into question. This proposal has three integrated Aims.",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-02-20T10:30:00Z",
      },
      {
        id: "b-aim1",
        type: "heading",
        content: "Aim 1. Re-examine the rigidification hypothesis with modern solvent models",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-02-21T09:15:00Z",
      },
      {
        id: "b-aim1-text",
        type: "text",
        content:
          "We will re-simulate the canonical 12-enzyme archaeal MD panel from our 2024 Nat Comm work using OPC and TIP4P-Ew water models at 363 K, comparing against our original TIP3P trajectories. We expect to falsify or refine the backbone-rigidification conclusion for at least 3 of the 12 systems.",
        source: "from-hypothesis",
        sourceRef: "h-2",
        authorId: "m-priya",
        createdAt: "2026-02-21T09:20:00Z",
        citations: [
          { paperId: "p-chen-2026", page: 2, sentence: "Under OPC water at 363 K, flexibility is 27–41% higher in loop regions." },
          { paperId: "p-dmitri-2025", page: 5, sentence: "~22% of published archaeal MD conclusions may be solvent-artifact-dependent." },
        ],
      },
      {
        id: "b-aim2",
        type: "heading",
        content: "Aim 2. Experimentally anchor the re-simulation with single-molecule FRET",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-02-25T11:00:00Z",
      },
      {
        id: "b-aim2-method",
        type: "methodology",
        content:
          "We will measure conformational dynamics in three representative archaeal enzymes at 25 °C and 85 °C using single-molecule FRET with established donor-acceptor labeling (Cy3/Cy5 on Cys mutants). Comparisons against our OPC-water MD trajectories will provide the first direct experimental anchor for the solvent-model debate.",
        subcontent: "Instrument: custom confocal smFRET rig (Schuler-group design). Sampling: ≥5000 molecules per condition. Labels: Cy3-Cy5 at positions identified by MD flexibility analysis.",
        source: "from-paper",
        sourceRef: "p-schuler-2023",
        authorId: "m-marcus",
        createdAt: "2026-02-25T11:12:00Z",
        editedByIds: ["m-priya"],
        editedAt: "2026-04-17T21:00:00Z",
        citations: [
          { paperId: "p-schuler-2023", page: 3, sentence: "Microsecond transitions are observed in three archaeal enzymes…" },
          { paperId: "p-imoto-2023", page: 4, sentence: "OPC water yields 3–7 kcal/mol lower unfolding barriers vs TIP3P." },
        ],
        commentThreadId: "t-1",
      },
      {
        id: "b-ai-insight-1",
        type: "ai-insight",
        content:
          "Your Aim 2 proposes smFRET as the experimental anchor for the solvent-model debate. Based on the team's library, you have 2 relevant methodology precedents (Schuler 2023, Imoto 2023) but no papers on Cy3/Cy5 labeling of archaeal enzymes specifically. Consider whether labeling strategy warrants a preliminary experiments paragraph — reviewers may flag feasibility here.",
        source: "ai-generated",
        sourceRef: "grounded in 12 papers",
        aiGroundedIn: ["p-schuler-2023", "p-imoto-2023", "p-kawamura-2024", "p-sali-2024"],
        authorId: "m-priya",
        createdAt: "2026-02-25T11:20:00Z",
      },
      {
        id: "b-aim3",
        type: "heading",
        content: "Aim 3. Scale to industrial continuous-flow biocatalysis",
        source: "hand-written",
        authorId: "m-hiro",
        createdAt: "2026-03-02T14:00:00Z",
      },
      {
        id: "b-aim3-goal",
        type: "text",
        content:
          "We will translate the mechanistic insights from Aims 1 and 2 into optimized enzyme variants for continuous-flow biocatalysis, targeting >200 h conversion retention at 85 °C — doubling the current state-of-the-art demonstrated by Williams 2025.",
        source: "hand-written",
        authorId: "m-hiro",
        createdAt: "2026-03-02T14:05:00Z",
        citations: [
          { paperId: "p-williams-2025", page: 3, sentence: "95% conversion retention over 120 h continuous operation at 75 °C." },
        ],
        commentThreadId: "t-2",
        flag: "contradiction",
        flagMessage: "Contradicts Aim 1 framing (rigidification as core mechanism vs. dynamics in biocatalysis)",
      },
      {
        id: "b-signif",
        type: "heading",
        content: "Significance",
        source: "hand-written",
        authorId: "m-hiro",
        createdAt: "2026-03-02T14:05:00Z",
      },
      {
        id: "b-signif-text",
        type: "text",
        content:
          "Roughly 22% of the published MD literature on archaeal thermostability may hinge on a solvent-model artifact (Volkov 2025). This proposal will resolve one of the largest methodological disagreements in computational biophysics of extremophiles, and translate the outcome into industrial biocatalytic capability that would otherwise require another decade of iteration in each of the two sub-fields.",
        source: "hand-written",
        authorId: "m-hiro",
        createdAt: "2026-03-03T10:20:00Z",
        editedByIds: ["m-priya"],
        editedAt: "2026-04-10T15:00:00Z",
        citations: [
          { paperId: "p-dmitri-2025", page: 5, sentence: "Up to 22% of published archaeal MD conclusions may be solvent-artifact-dependent." },
        ],
      },
      {
        id: "b-innov",
        type: "heading",
        content: "Innovation",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-03-04T09:00:00Z",
      },
      {
        id: "b-innov-1",
        type: "text",
        content:
          "We propose the first systematic, matched OPC-vs-TIP3P re-examination of an established archaeal MD corpus, paired with direct smFRET measurement. This is methodologically novel: no prior study has combined force-field cross-validation with single-molecule experimental anchoring at industrial temperatures.",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-03-04T09:15:00Z",
      },
      {
        id: "b-innov-2",
        type: "text",
        content:
          "Our secondary innovation is importing the activation-energy framework from ceramic thermal-aging (Rocha 2024) to enzyme denaturation kinetics — a cross-disciplinary bridge with no prior citations in the biophysics literature. If successful, this would provide a unified kinetic model for enzyme half-life prediction at arbitrary industrial temperatures.",
        source: "from-paper",
        sourceRef: "p-rocha-2024",
        authorId: "m-marcus",
        createdAt: "2026-04-18T06:30:00Z",
        citations: [{ paperId: "p-rocha-2024", page: 2, sentence: "Our activation-energy framework is general to activated thermal degradation processes." }],
      },
      {
        id: "b-approach",
        type: "heading",
        content: "Approach",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-03-05T10:00:00Z",
      },
      {
        id: "b-approach-plan",
        type: "experimental-plan",
        content:
          "Experimental plan for Aim 1 OPC re-simulation:\n• Hypothesis: Under OPC water at 363 K, ≥3 of the 12 archaeal enzymes from our panel will show flexibility patterns inconsistent with rigidification.\n• Procedure: 1μs production simulations per enzyme per water model; triplicate replicates. RMSF, CMD, and FES analysis.\n• Expected outcome: overturn or refine rigidification for ≥3/12 systems.\n• Success criterion: >20% RMSF divergence in loop regions between OPC and TIP3P for ≥3 systems; AND qualitative disagreement with the published rigidification conclusion.",
        subcontent: "Timeline: months 1–9. Compute: 400k GPU-hours estimated. Personnel: Priya (lead), Marcus (FF portability), Dmitri (artifact audit).",
        source: "from-hypothesis",
        sourceRef: "h-2",
        authorId: "m-priya",
        createdAt: "2026-03-05T10:30:00Z",
      },
      {
        id: "b-ref-key",
        type: "reference",
        content: "Key references (17 papers from the team library):",
        source: "from-synthesis",
        sourceRef: "syn-thermostability",
        authorId: "m-priya",
        createdAt: "2026-03-05T11:00:00Z",
      },
      {
        id: "b-note-1",
        type: "research-note",
        content:
          "Met with Fukuda group this week re: T. kodakarensis expression strains. They will share their growth-temperature-controlled strain library if we include them as consultants on Aim 2. Worth negotiating.",
        source: "hand-written",
        authorId: "m-hiro",
        createdAt: "2026-04-15T17:00:00Z",
      },
      {
        id: "b-callout-reviewers",
        type: "callout",
        content:
          "⚠️ Reviewer concern to preempt: 'If your own 2024 paper used TIP3P, how do we know you're not just backing a new trend?' — we need a paragraph in Approach that cites Dmitri 2025's systematic review and shows the conclusion is field-wide.",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-04-17T14:20:00Z",
        tabId: "notes",
        tags: ["reviewer-prep", "aim-1"],
      },

      // ===== Protocol tab =====
      {
        id: "b-date-protocol",
        type: "date-header",
        content: "",
        dateISO: "2026-04-15",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-04-15T09:00:00Z",
        tabId: "protocol",
      },
      {
        id: "b-proto-title",
        type: "heading",
        content: "OPC water re-simulation protocol (Aim 1)",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-04-15T09:05:00Z",
        tabId: "protocol",
        tags: ["md", "opc"],
      },
      {
        id: "b-proto-method",
        type: "methodology",
        content:
          "1. Prepare starting structures from PDB entries for the 12 archaeal enzymes in the Kawamura 2024 panel.\n2. Solvate each in an OPC water box with 150 mM NaCl, min. 12 Å padding.\n3. Energy minimize (1000 steps steepest descent + 1000 steps conjugate gradient).\n4. Equilibrate NVT → NPT (2 × 500 ps) at 363 K.\n5. Production: 3 × 1 μs replicas per system. Save every 100 ps.\n6. Analysis: per-residue RMSF, loop-region comparison with TIP3P trajectories, FES along unfolding coordinate.",
        subcontent: "Force field: AMBER-ff14SB. Integrator: Langevin, 2 fs step. Cutoff: 10 Å with PME. Pressure: 1 atm Monte Carlo barostat.",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-04-15T09:15:00Z",
        tabId: "protocol",
        tags: ["md", "amber", "opc"],
      },
      {
        id: "b-proto-table",
        type: "table",
        content: "System matrix for Aim 1 re-simulation",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-04-15T09:30:00Z",
        tabId: "protocol",
        tags: ["md", "planning"],
        tableData: {
          caption: "Systems × water models × replicas. All at 363 K.",
          headers: ["PDB", "Organism", "Class", "TIP3P (Kawamura 2024)", "OPC (this study)", "TIP4P-Ew"],
          rows: [
            ["1WNK", "T. kodakarensis", "α/β hydrolase", "done", "3 × 1 μs", "1 × 1 μs"],
            ["2E13", "P. furiosus", "Chaperonin", "done", "3 × 1 μs", "—"],
            ["1J9Y", "S. acidocaldarius", "Carboxylesterase", "done", "3 × 1 μs", "1 × 1 μs"],
            ["3AJX", "P. horikoshii", "Isomerase", "done", "3 × 1 μs", "—"],
            ["1WDD", "T. kodakarensis", "Kinase", "done", "3 × 1 μs", "1 × 1 μs"],
            ["4OMC", "P. furiosus", "Oxidase", "done", "3 × 1 μs", "—"],
          ],
        },
      },

      // ===== Notes tab — April lab journal =====
      {
        id: "b-date-lab",
        type: "date-header",
        content: "",
        dateISO: "2026-04-17",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-04-17T21:15:00Z",
        tabId: "notes",
      },
      {
        id: "b-image-gel",
        type: "image",
        content: "Ligation check — pAS329 → EGFR insert",
        source: "hand-written",
        authorId: "m-marcus",
        createdAt: "2026-04-17T22:42:00Z",
        tabId: "notes",
        tags: ["wet-lab", "ligation"],
        imageData: {
          placeholder: "pAS329_ligation_check.png — ethidium-stained 0.8% agarose gel, 30min @ 100V",
          caption: "Tuesday ligation check (pAS329 → EGFR). Lane 1: ladder. Lane 2: undigested. Lane 3: digested vector. Lane 4: insert DNA. Lane 5: ligation tube.",
          annotations: [
            { label: "Lane 1: DNA ladder", y: 10 },
            { label: "Lane 2: undigested", y: 25 },
            { label: "Lane 3: digested vector", y: 40 },
            { label: "Lane 4: insert DNA", y: 55 },
            { label: "Lane 5: ligation tube", y: 70 },
          ],
        },
      },

      // ===== Relevant items tab =====
      {
        id: "b-rel-header",
        type: "heading",
        content: "Papers and datasets tagged to this project",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-04-10T09:00:00Z",
        tabId: "relevant",
      },
      {
        id: "b-rel-refs",
        type: "reference",
        content: "47 papers from the team library are cited across this notebook (auto-indexed):",
        source: "from-synthesis",
        sourceRef: "syn-thermostability",
        authorId: "m-priya",
        createdAt: "2026-04-10T09:05:00Z",
        tabId: "relevant",
        tags: ["index"],
      },
      {
        id: "b-rel-data",
        type: "data",
        content: "Linked datasets",
        subcontent: "ThermoMutDB · Kawamura 2024 TIP3P trajectories (internal, 48 TB) · Chen 2026 OPC trajectories (bioRxiv supplementary)",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-04-10T09:10:00Z",
        tabId: "relevant",
        tags: ["datasets"],
      },

      // ===== Metadata tab =====
      {
        id: "b-meta-table",
        type: "table",
        content: "Proposal metadata",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-02-20T10:35:00Z",
        tabId: "metadata",
        tableData: {
          headers: ["Field", "Value"],
          rows: [
            ["Funding mechanism", "NIH R01 (Research Project)"],
            ["Study section", "MSFD (Macromolecular Structure & Function D)"],
            ["PI", "Hiro Kawamura"],
            ["Co-I", "Priya Menon (postdoc)"],
            ["External collaborator", "Dr. Amina Okafor (Oxford) — commenter"],
            ["Submission cycle", "2026-09 (due 2026-06-05)"],
            ["Budget", "$1.95M direct / 5 years"],
            ["Human subjects", "No"],
            ["Animal subjects", "No"],
          ],
        },
      },

      // ===== Reviewer prep (user-created) tab =====
      {
        id: "b-rev-date",
        type: "date-header",
        content: "",
        dateISO: "2026-04-16",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-04-16T09:00:00Z",
        tabId: "reviewers",
      },
      {
        id: "b-rev-q1",
        type: "callout",
        content: "Anticipated Reviewer 1: \"Why should we believe OPC is the right choice and not just the new fashion?\"",
        source: "hand-written",
        authorId: "m-priya",
        createdAt: "2026-04-16T09:05:00Z",
        tabId: "reviewers",
        tags: ["reviewer-prep", "opc"],
      },
      {
        id: "b-rev-a1",
        type: "ai-insight",
        content:
          "Suggested response framing: Lead with Volkov 2025's systematic review (22% artifact-risk). Cite Imoto 2023's explicit-solvent free-energies matching experiment. Add a preliminary figure showing the TIP3P→OPC delta on one representative enzyme with smFRET overlay (leveraging Schuler 2023). Close with: 'We don't claim TIP3P is wrong everywhere — we claim the field should know which conclusions are solvent-robust and which are not.'",
        source: "ai-generated",
        sourceRef: "grounded in 4 team papers",
        aiGroundedIn: ["p-dmitri-2025", "p-imoto-2023", "p-schuler-2023", "p-chen-2026"],
        authorId: "m-priya",
        createdAt: "2026-04-16T09:10:00Z",
        tabId: "reviewers",
        tags: ["reviewer-prep", "rebuttal"],
      },
    ],
  },
  {
    id: "nb-manuscript-thermo",
    title: "Manuscript — Structural determinants of thermostability in archaeal enzymes",
    description: "Short-format paper responding to Chen 2026 with our own OPC-water re-examination results.",
    mode: "manuscript",
    status: "draft",
    createdAt: "2026-03-25T09:00:00Z",
    updatedAt: "2026-04-16T14:00:00Z",
    linkedSyntheses: ["syn-thermostability"],
    linkedHypotheses: ["h-2"],
    collaborators: [
      { memberId: "m-priya", role: "owner", scope: "whole", status: "active" },
      { memberId: "m-marcus", role: "editor", scope: "whole", status: "active" },
      { memberId: "m-hiro", role: "editor", scope: "whole", status: "active" },
    ],
    activity: [
      { id: "act-m-1", actorId: "m-marcus", action: "created notebook", at: "2026-03-25T09:00:00Z" },
      { id: "act-m-2", actorId: "m-priya", action: "added abstract draft", at: "2026-03-28T11:00:00Z" },
    ],
    comments: [],
    blocks: [
      { id: "bm-title", type: "heading", content: "Structural determinants of thermostability in archaeal enzymes: a solvent-model-aware re-examination", source: "hand-written", authorId: "m-priya", createdAt: "2026-03-25T09:00:00Z" },
      { id: "bm-abs", type: "text", content: "We re-simulate the canonical 12-enzyme archaeal MD panel with OPC and TIP4P-Ew water models and compare against TIP3P trajectories. Across three systems (TK1687, PF0974, Sso-AdhB) OPC reveals loop-region flexibility incompatible with the strict rigidification hypothesis, while in the remaining nine the rigidification pattern persists. We propose a refined 'regional rigidification' model.", source: "hand-written", authorId: "m-priya", createdAt: "2026-03-28T11:00:00Z" },
    ],
  },
  {
    id: "nb-peer-review",
    title: "Peer-Review Response — Nature Communications Reviewer 2",
    description: "Point-by-point response to Reviewer 2 comments on 'Force-field portability for de novo designed thermostable enzymes' (Marcus & Priya).",
    mode: "peer-review",
    status: "in-review",
    createdAt: "2026-04-08T10:00:00Z",
    updatedAt: "2026-04-17T16:00:00Z",
    linkedSyntheses: ["syn-forcefield"],
    linkedHypotheses: [],
    collaborators: [
      { memberId: "m-marcus", role: "owner", scope: "whole", status: "active" },
      { memberId: "m-priya", role: "editor", scope: "whole", status: "active" },
    ],
    activity: [
      { id: "act-pr-1", actorId: "m-marcus", action: "uploaded reviewer letter", at: "2026-04-08T10:00:00Z" },
      { id: "act-pr-2", actorId: "m-marcus", action: "brain drafted 4 responses", at: "2026-04-08T10:05:00Z" },
    ],
    comments: [],
    blocks: [
      { id: "bp-title", type: "heading", content: "Point-by-point responses to Reviewer 2", source: "hand-written", authorId: "m-marcus", createdAt: "2026-04-08T10:00:00Z" },
      { id: "bp-r1-q", type: "callout", content: "Reviewer 2, Point 1: 'The RMSF divergence between AMBER and CHARMM is not surprising and has been known since the 2000s. What is novel here?'", source: "hand-written", authorId: "m-marcus", createdAt: "2026-04-08T10:01:00Z" },
      { id: "bp-r1-a", type: "ai-insight", content: "We thank the reviewer for the challenge. The novelty is not the existence of RMSF divergence between force fields (which is indeed long-known), but the *portability benchmark methodology* — specifically, a quantitative framework that allows de novo design teams to know, before expensive wet-lab validation, whether their force-field choice materially affects design outcomes. As our Table 2 shows, 10–18% RMSF divergence on the Baker-lab designs maps onto a 0.3–1.1 pLDDT drop in downstream AlphaFold2 validation — a concrete, actionable number that previously required ad-hoc per-project experimentation to establish.", source: "ai-generated", sourceRef: "grounded in 8 team papers", aiGroundedIn: ["p-marcus-2025", "p-baker-2024", "p-lindorff-2022"], authorId: "m-marcus", createdAt: "2026-04-08T10:05:00Z" },
      { id: "bp-r2-q", type: "callout", content: "Reviewer 2, Point 2: 'The sample size of 3 force fields is too small to draw general portability conclusions.'", source: "hand-written", authorId: "m-marcus", createdAt: "2026-04-08T10:02:00Z" },
      { id: "bp-r2-a", type: "ai-insight", content: "We agree 3 force fields is a lower bound. Our choice reflects the de facto standard: >90% of published de novo design MD validations use one of AMBER-ff19SB, CHARMM36m, or AMOEBA (Supplementary Table 3, drawn from the 87 papers surveyed by Volkov et al. 2025). A portability benchmark across the three field-standard choices is therefore representative of the decision space any practitioner faces today. We have added a supplementary analysis with OPLS4 to provide a fourth data point.", source: "ai-generated", sourceRef: "grounded in 5 team papers", aiGroundedIn: ["p-dmitri-2025", "p-marcus-2025"], authorId: "m-marcus", createdAt: "2026-04-08T10:06:00Z" },
    ],
  },
];

export function notebookById(id: string): Notebook | undefined {
  return notebooks.find((n) => n.id === id);
}
