import type { Paper } from "../types";

export const papers: Paper[] = [
  {
    id: "p-chen-2026",
    title: "OPC water model reveals underestimated flexibility in hyperthermophile enzymes at simulated industrial temperatures",
    authors: ["a-chen-bx", "a-lindorff"],
    year: 2026,
    venue: "bioRxiv",
    source: "biorxiv",
    externalId: "bioRxiv 2026.01.14.578921",
    externalUrl: "https://www.biorxiv.org/content/10.1101/2026.01.14.578921v1",
    doi: "10.1101/2026.01.14.578921",
    abstract:
      "Classical all-atom molecular dynamics studies of hyperthermophile proteins have consistently relied on the TIP3P water model, which systematically underestimates solvation dynamics at temperatures above 350 K. Using OPC water at 363 K, we re-examine three archaeal enzymes previously reported as rigid and find markedly greater backbone flexibility in loop regions. This result disagrees with the conclusions of Kawamura et al. (2024) and implies that the widely cited mechanism of thermostability via rigidification is at least partially an artifact of the solvent model. We argue for re-running key literature-standard simulations with corrected water models before using the results to inform de novo design.",
    tags: ["thermostability", "MD", "force field", "archaea", "OPC", "TIP3P"],
    disciplines: ["biophysics", "biochem"],
    methodology: ["MD simulation", "OPC water model"],
    findings: ["contradicts rigidification hypothesis", "force-field-dependent flexibility"],
    confidence: 0.64,
    replicated: false,
    readByTeam: ["m-priya"],
    citationCount: 2,
  },
  {
    id: "p-kawamura-2024",
    title: "Backbone rigidification as a common mechanism for thermal stability in archaeal enzymes",
    authors: ["a-hiro", "a-priya", "a-marcus"],
    year: 2024,
    venue: "Nature Communications",
    source: "nature",
    externalId: "Nat Commun 15, 4872 (2024)",
    externalUrl: "https://www.nature.com/articles/s41467-024-04872-7",
    doi: "10.1038/s41467-024-04872-7",
    abstract:
      "We report microsecond-scale molecular dynamics simulations of twelve archaeal enzymes from Thermococcus kodakarensis and Pyrococcus furiosus across 298–363 K. Across all systems we observe a statistically consistent reduction in backbone RMSF at the thermostable homologs' key loop regions relative to their mesophilic counterparts. We propose backbone rigidification — not increased salt-bridge networks — as the dominant driver of hyperthermostability in this clade.",
    tags: ["thermostability", "MD", "archaea", "backbone rigidification"],
    disciplines: ["biophysics", "biochem", "microbio"],
    methodology: ["MD simulation", "TIP3P water model", "AMBER force field"],
    findings: ["rigidification hypothesis", "reduced RMSF in thermostable homologs"],
    confidence: 0.82,
    replicated: true,
    readByTeam: ["m-priya", "m-hiro", "m-marcus", "m-zara"],
    citationCount: 148,
  },
  {
    id: "p-abramson-2024",
    title: "Accurate structure prediction of biomolecular interactions with AlphaFold 3",
    authors: ["a-abramson", "a-jumper"],
    year: 2024,
    venue: "Nature",
    source: "nature",
    externalId: "Nature 630, 493–500 (2024)",
    externalUrl: "https://www.nature.com/articles/s41586-024-07487-w",
    doi: "10.1038/s41586-024-07487-w",
    abstract:
      "AlphaFold 3 extends structure prediction beyond single-chain proteins to arbitrary biomolecular complexes with significantly improved accuracy on protein-ligand, protein-nucleic acid, and protein-protein interactions.",
    tags: ["AlphaFold", "structure prediction", "deep learning"],
    disciplines: ["cs", "biophysics"],
    methodology: ["diffusion model", "attention", "DL-based folding"],
    findings: ["SOTA on complexes", "improved ligand accuracy"],
    confidence: 0.95,
    replicated: true,
    readByTeam: ["m-priya", "m-hiro", "m-marcus", "m-zara", "m-dmitri"],
    citationCount: 2840,
    landmark: true,
  } as Paper & { landmark: true },
  {
    id: "p-jumper-2021",
    title: "Highly accurate protein structure prediction with AlphaFold",
    authors: ["a-jumper"],
    year: 2021,
    venue: "Nature",
    source: "nature",
    externalId: "Nature 596, 583–589 (2021)",
    externalUrl: "https://www.nature.com/articles/s41586-021-03819-2",
    doi: "10.1038/s41586-021-03819-2",
    abstract:
      "AlphaFold 2 achieves near-experimental accuracy on the CASP14 structure prediction benchmark using an attention-based neural architecture trained on evolutionary and structural data.",
    tags: ["AlphaFold", "CASP14", "structure prediction"],
    disciplines: ["cs", "biophysics"],
    methodology: ["attention", "transformer", "Evoformer"],
    findings: ["CASP14 state-of-the-art", "sub-angstrom accuracy on CASP domains"],
    confidence: 0.98,
    replicated: true,
    readByTeam: ["m-priya", "m-hiro", "m-marcus", "m-zara", "m-dmitri"],
    citationCount: 19850,
  },
  {
    id: "p-baker-2024",
    title: "De novo design of ultra-thermostable α/β enzymes via diffusion-based backbone generation",
    authors: ["a-baker"],
    year: 2024,
    venue: "Science",
    source: "science",
    externalId: "Science 384, 215–221 (2024)",
    externalUrl: "https://www.science.org/doi/10.1126/science.adk2024",
    doi: "10.1126/science.adk2024",
    abstract:
      "Using RFdiffusion coupled to an AlphaFold2-based validation loop we design seven α/β hydrolases that retain activity after incubation at 95 °C for 48 hours, outperforming all known natural homologs.",
    tags: ["de novo design", "RFdiffusion", "thermostability"],
    disciplines: ["cs", "biochem", "biophysics"],
    methodology: ["RFdiffusion", "AlphaFold2 validation"],
    findings: ["7 ultra-thermostable designs", "activity at 95 °C 48h"],
    confidence: 0.88,
    replicated: false,
    readByTeam: ["m-priya", "m-hiro", "m-marcus"],
    citationCount: 712,
  },
  {
    id: "p-patel-2025",
    title: "Structure-guided stabilization of industrial esterases using cross-domain evolutionary constraints",
    authors: ["a-patel"],
    year: 2025,
    venue: "PNAS",
    source: "pnas",
    externalId: "PNAS 122(7) e2418221122",
    externalUrl: "https://www.pnas.org/doi/10.1073/pnas.2418221122",
    doi: "10.1073/pnas.2418221122",
    abstract:
      "By borrowing evolutionary constraints from archaeal hyperthermostable lipases, we stabilize three mesophilic esterases used in industrial biocatalysis, raising their Tm by 18–24 °C with minimal impact on kcat.",
    tags: ["esterase", "stability", "evolutionary constraints"],
    disciplines: ["biochem", "biophysics"],
    methodology: ["structure-guided engineering", "evolutionary coupling"],
    findings: ["18–24 °C Tm gain", "retained kcat"],
    confidence: 0.86,
    replicated: true,
    readByTeam: ["m-priya", "m-marcus"],
    citationCount: 41,
  },
  {
    id: "p-ovchinnikov-2023",
    title: "ESM-2 embeddings capture protein thermostability information orthogonal to evolutionary conservation",
    authors: ["a-ovchinnikov"],
    year: 2023,
    venue: "arXiv",
    source: "arxiv",
    externalId: "arXiv:2311.05021",
    externalUrl: "https://arxiv.org/abs/2311.05021",
    doi: "10.48550/arXiv.2311.05021",
    abstract:
      "We show that ESM-2 embeddings contain orthogonal signal to PSSM-style conservation when predicting Tm, and that combining both sources yields a 14% rank-correlation improvement on the ThermoMutDB benchmark.",
    tags: ["ESM-2", "protein language model", "Tm prediction"],
    disciplines: ["cs", "biophysics"],
    methodology: ["protein language model", "embedding probe"],
    findings: ["orthogonal Tm signal", "+14% on ThermoMutDB"],
    confidence: 0.83,
    replicated: true,
    readByTeam: ["m-priya", "m-marcus", "m-dmitri"],
    citationCount: 285,
  },
  {
    id: "p-schuler-2023",
    title: "Single-molecule FRET of hyperthermophile proteins reveals unexpected slow dynamics at 85 °C",
    authors: ["a-schuler"],
    year: 2023,
    venue: "Cell",
    source: "cell",
    externalId: "Cell 186, 3120–3135 (2023)",
    externalUrl: "https://www.cell.com/cell/fulltext/S0092-8674(23)00621-5",
    doi: "10.1016/j.cell.2023.06.021",
    abstract:
      "Using single-molecule FRET we measure slow conformational dynamics in three archaeal enzymes at physiological temperatures, observing microsecond transitions inconsistent with the prevailing rigidification picture.",
    tags: ["smFRET", "thermostability", "dynamics"],
    disciplines: ["biophysics"],
    methodology: ["single-molecule FRET"],
    findings: ["slow conformational dynamics", "contradicts pure rigidification"],
    confidence: 0.87,
    replicated: false,
    readByTeam: ["m-priya", "m-hiro", "m-zara"],
    citationCount: 92,
  },
  {
    id: "p-lindorff-2022",
    title: "Comparison of AMBER and CHARMM36m force fields for long timescale simulations of archaeal proteins",
    authors: ["a-lindorff"],
    year: 2022,
    venue: "J. Chem. Theory Comput.",
    source: "acm",
    externalId: "JCTC 18(9) 5500–5512",
    externalUrl: "https://pubs.acs.org/doi/10.1021/acs.jctc.2c00471",
    doi: "10.1021/acs.jctc.2c00471",
    abstract:
      "Systematic comparison across 12 archaeal globular proteins shows AMBER-ff14SB provides superior loop-region accuracy for thermostable variants relative to CHARMM36m, at the cost of slight over-rigidification on mesophilic controls.",
    tags: ["force field", "AMBER", "CHARMM36m"],
    disciplines: ["biophysics"],
    methodology: ["MD simulation", "force field comparison"],
    findings: ["AMBER better for loop accuracy", "CHARMM slight mesophilic under-rigidification"],
    confidence: 0.8,
    replicated: true,
    readByTeam: ["m-priya", "m-hiro", "m-marcus"],
    citationCount: 138,
  },
  {
    id: "p-sali-2024",
    title: "Integrative structure modeling of Pyrococcus furiosus chaperones: cryo-EM + MD",
    authors: ["a-sali"],
    year: 2024,
    venue: "Cell",
    source: "cell",
    externalId: "Cell 187, 1800–1815 (2024)",
    externalUrl: "https://www.cell.com/cell/fulltext/S0092-8674(24)00103-7",
    doi: "10.1016/j.cell.2024.02.018",
    abstract:
      "Combining high-resolution cryo-EM with microsecond MD we build an integrative model of the P. furiosus PfuGroEL assembly, revealing substrate recognition pockets distinct from mesophilic homologs.",
    tags: ["cryo-EM", "integrative modeling", "chaperonin"],
    disciplines: ["biophysics", "microbio"],
    methodology: ["cryo-EM", "MD simulation"],
    findings: ["novel substrate pocket", "distinct from GroEL"],
    confidence: 0.9,
    replicated: true,
    readByTeam: ["m-priya", "m-hiro"],
    citationCount: 58,
  },
  {
    id: "p-nguyen-2025",
    title: "Proteome-wide thermostability profiling of Sulfolobus acidocaldarius under industrial process conditions",
    authors: ["a-nguyen"],
    year: 2025,
    venue: "PubMed",
    source: "pubmed",
    externalId: "PMID 39884217",
    externalUrl: "https://pubmed.ncbi.nlm.nih.gov/39884217",
    doi: "10.1038/s41589-025-01901-8",
    abstract:
      "Mass-spectrometry thermal proteome profiling of S. acidocaldarius under industrial acid-stress conditions identifies 48 proteins with divergent melting behavior vs. the organism's physiological range, highlighting candidate scaffolds for directed evolution.",
    tags: ["thermostability", "proteomics", "Sulfolobus"],
    disciplines: ["microbio", "biochem"],
    methodology: ["thermal proteome profiling", "mass spectrometry"],
    findings: ["48 divergent-Tm proteins", "candidate evolution scaffolds"],
    confidence: 0.78,
    replicated: false,
    readByTeam: ["m-priya", "m-zara"],
    citationCount: 34,
  },
  {
    id: "p-rocha-2024",
    title: "Activation-energy framework for thermal aging in ceramic catalysts",
    authors: ["a-rocha"],
    year: 2024,
    venue: "Nature Materials",
    source: "nature",
    externalId: "Nat Mater 23, 780–788 (2024)",
    externalUrl: "https://www.nature.com/articles/s41563-024-01842-x",
    doi: "10.1038/s41563-024-01842-x",
    abstract:
      "We derive a modified Arrhenius activation-energy framework for thermal aging of perovskite catalysts that accounts for cooperative defect migration, with broad applicability to any activated thermal degradation process.",
    tags: ["activation energy", "thermal aging", "ceramics"],
    disciplines: ["materials"],
    methodology: ["kinetic modeling", "Arrhenius analysis"],
    findings: ["cooperative defect migration", "general activation-energy framework"],
    confidence: 0.88,
    replicated: true,
    readByTeam: [],
    citationCount: 110,
    unknownUnknown: true,
  } as Paper & { unknownUnknown: true },
  {
    id: "p-williams-2025",
    title: "Continuous-flow biocatalysis with immobilized extremophile esterases: a process-engineering pilot",
    authors: ["a-williams"],
    year: 2025,
    venue: "ACS Catal.",
    source: "acm",
    externalId: "ACS Catal. 15, 13201–13214",
    externalUrl: "https://pubs.acs.org/doi/10.1021/acscatal.5c02412",
    doi: "10.1021/acscatal.5c02412",
    abstract:
      "We demonstrate a 120 h continuous-flow pilot of an immobilized archaeal esterase at 75 °C with >95% conversion retention, highlighting the feasibility of extremophile enzymes in industrial process streams.",
    tags: ["continuous flow", "biocatalysis", "immobilization"],
    disciplines: ["materials", "biochem"],
    methodology: ["process engineering", "enzyme immobilization"],
    findings: ["120h conversion retention", "industrial feasibility"],
    confidence: 0.84,
    replicated: false,
    readByTeam: ["m-priya"],
    citationCount: 29,
  },
  {
    id: "p-imoto-2023",
    title: "Explicit solvent effects on free-energy landscapes of hyperthermophile unfolding",
    authors: ["a-imoto"],
    year: 2023,
    venue: "JCP",
    source: "acm",
    externalId: "J. Chem. Phys. 159, 174101",
    externalUrl: "https://pubs.aip.org/aip/jcp/article/159/17/174101",
    doi: "10.1063/5.0165221",
    abstract:
      "Systematic free-energy calculations with explicit TIP4P-Ew and OPC water models reveal 3–7 kcal/mol differences in unfolding barriers, with OPC yielding better agreement with experimentally measured melting temperatures.",
    tags: ["free energy", "solvent", "OPC", "TIP4P-Ew"],
    disciplines: ["biophysics"],
    methodology: ["free energy perturbation", "explicit solvent MD"],
    findings: ["OPC matches experiment better", "3–7 kcal/mol solvent effect"],
    confidence: 0.83,
    replicated: true,
    readByTeam: ["m-priya", "m-hiro", "m-marcus"],
    citationCount: 68,
  },
  {
    id: "p-chen-heat-shock-2024",
    title: "Heat-shock protein 90 dynamics in tumor microenvironments: shared activation motifs with archaeal chaperones",
    authors: ["a-chen-bx"],
    year: 2024,
    venue: "eLife",
    source: "elife",
    externalId: "eLife 2024;13:e88721",
    externalUrl: "https://elifesciences.org/articles/88721",
    doi: "10.7554/eLife.88721",
    abstract:
      "Comparative analysis of HSP90 activation motifs across cancer cell lines and archaeal chaperones reveals shared allosteric pathways, suggesting cross-disciplinary methodological transfer is possible.",
    tags: ["HSP90", "chaperone", "allostery", "cancer"],
    disciplines: ["biochem", "biophysics"],
    methodology: ["comparative structural analysis", "allosteric mapping"],
    findings: ["shared activation motifs", "cross-system allostery"],
    confidence: 0.76,
    replicated: false,
    readByTeam: [],
    citationCount: 19,
    unknownUnknown: true,
  } as Paper & { unknownUnknown: true },
  {
    id: "p-rocha-dl-2024",
    title: "Deep-learning prediction of ceramic failure under cyclic thermal load",
    authors: ["a-rocha"],
    year: 2024,
    venue: "npj Computational Materials",
    source: "nature",
    externalId: "npj Comp Mater 10, 92",
    externalUrl: "https://www.nature.com/articles/s41524-024-01244-9",
    doi: "10.1038/s41524-024-01244-9",
    abstract:
      "We train a graph neural network on 40k cyclic-thermal-load experiments and show the model discovers an activation-energy-like feature directly applicable to any activated-failure process.",
    tags: ["deep learning", "ceramic failure", "GNN", "cyclic thermal"],
    disciplines: ["materials", "cs"],
    methodology: ["graph neural network", "cyclic thermal experiments"],
    findings: ["DL-discovered activation-energy feature", "transfer potential"],
    confidence: 0.82,
    replicated: false,
    readByTeam: [],
    citationCount: 47,
    unknownUnknown: true,
  } as Paper & { unknownUnknown: true },
  {
    id: "p-freund-2024",
    title: "Evolutionary drivers of thermostability: when selection pressure stops",
    authors: ["a-freund"],
    year: 2024,
    venue: "Nature Ecology & Evolution",
    source: "nature",
    externalId: "Nat Ecol Evol 8, 1520–1532",
    externalUrl: "https://www.nature.com/articles/s41559-024-02391-y",
    doi: "10.1038/s41559-024-02391-y",
    abstract:
      "Phylogenetic reconstruction of 1,400 enzyme families shows selection for thermostability plateaus at the environmental maximum; further stability gains must be evolutionary by-products.",
    tags: ["evolution", "thermostability", "phylogenetics"],
    disciplines: ["microbio", "biochem"],
    methodology: ["ancestral sequence reconstruction", "phylogenetics"],
    findings: ["selection plateau", "further stability is by-product"],
    confidence: 0.85,
    replicated: true,
    readByTeam: ["m-priya", "m-zara", "m-hiro"],
    citationCount: 91,
  },
  {
    id: "p-dmitri-2025",
    title: "TIP3P artifacts in the published archaeal MD literature: a systematic review",
    authors: ["a-dmitri"],
    year: 2025,
    venue: "bioRxiv",
    source: "biorxiv",
    externalId: "bioRxiv 2025.11.02.589102",
    externalUrl: "https://www.biorxiv.org/content/10.1101/2025.11.02.589102v1",
    doi: "10.1101/2025.11.02.589102",
    abstract:
      "Systematic survey of 87 published MD studies of archaeal proteins finds 74 rely exclusively on TIP3P at >330 K; based on benchmark data we estimate up to 22% of conclusions may be solvent-artifact-dependent.",
    tags: ["TIP3P", "solvent artifact", "review"],
    disciplines: ["biophysics"],
    methodology: ["systematic review"],
    findings: ["74/87 studies TIP3P-only", "22% artifact-risk estimate"],
    confidence: 0.72,
    replicated: false,
    readByTeam: ["m-priya", "m-hiro", "m-marcus", "m-dmitri"],
    citationCount: 8,
  },
  {
    id: "p-marcus-2025",
    title: "Force-field portability for de novo designed thermostable enzymes",
    authors: ["a-marcus", "a-priya"],
    year: 2025,
    venue: "bioRxiv",
    source: "biorxiv",
    externalId: "bioRxiv 2025.08.15.568420",
    externalUrl: "https://www.biorxiv.org/content/10.1101/2025.08.15.568420v1",
    doi: "10.1101/2025.08.15.568420",
    abstract:
      "Re-simulation of the Baker-lab α/β hydrolase designs across AMBER-ff19SB, CHARMM36m, and OpenMM AMOEBA shows qualitative agreement but 10–18% RMSF divergence; we propose a portability benchmark.",
    tags: ["force field", "de novo", "RMSF"],
    disciplines: ["biophysics", "cs"],
    methodology: ["MD simulation", "force-field cross-validation"],
    findings: ["10–18% RMSF divergence", "portability benchmark proposal"],
    confidence: 0.75,
    replicated: false,
    readByTeam: ["m-priya", "m-marcus", "m-hiro"],
    citationCount: 14,
  },
  {
    id: "p-zara-2024",
    title: "Psychrophilic protein flexibility: what directed evolution hasn't touched",
    authors: ["a-zara"],
    year: 2024,
    venue: "bioRxiv",
    source: "biorxiv",
    externalId: "bioRxiv 2024.12.01.567890",
    externalUrl: "https://www.biorxiv.org/content/10.1101/2024.12.01.567890v1",
    doi: "10.1101/2024.12.01.567890",
    abstract:
      "A scoping review finds only 6 papers apply modern directed-evolution methods (MutaT7, PACE, DOCK) to psychrophilic proteins, despite the clear biotechnological potential in low-temperature biocatalysis.",
    tags: ["psychrophile", "directed evolution", "scoping review"],
    disciplines: ["biochem", "microbio"],
    methodology: ["scoping review"],
    findings: ["gap: only 6 directed-evolution papers on psychrophiles"],
    confidence: 0.9,
    replicated: false,
    readByTeam: ["m-priya", "m-zara"],
    citationCount: 7,
  },
];

export function paperById(id: string): Paper | undefined {
  return papers.find((p) => p.id === id);
}

export function papersByIds(ids: string[]): Paper[] {
  return ids.map((id) => paperById(id)).filter(Boolean) as Paper[];
}
